# https://github.com/electron/electron/blob/master/.travis.yml
git:
  depth: 10

notifications:
  email: false

before_install:
  - export BOTO_CONFIG=/dev/null

language: node_js
node_js:
  - "9.3.0"
os:
  - linux
  - osx
env:
  - TARGET_ARCH=x64
osx_image: xcode7.3

matrix:
  include:
    - os: osx
  #   - os: linux
  #     env: TARGET_ARCH=arm
  #   - os: linux
  #     env: TARGET_ARCH=ia32
  #   - os: linux
  #     env: TARGET_ARCH=arm64
  # allow_failures:

script: 'bash ./scripts/cibuild.sh'
